version: '3.1'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysqlvolume:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: netology1201
      MYSQL_USER: nedorezov
      MYSQL_PASSWORD: 1
volumes:
  mysqlvolume: {}