---
- name: Load Kafka tar.gz and unarchive
  hosts: all

  tasks:
  - name: Create destination dir
    ansible.builtin.file:
      path: /tmp/kafka
      state: directory
      mode: '0755'

  - name: Load archive from src and unpack
    ansible.builtin.unarchive:
      src: https://downloads.apache.org/kafka/3.3.1/kafka_2.12-3.3.1.tgz
      remote_src: true
      dest: /tmp/kafka