
- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Install packet "apache2"
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Set index.html
  ansible.builtin.copy:
    content: |
      <!DOCTYPE html>
      <html><body>
      <h1>Hostname: {{ ansible_facts['hostname'] }}</h1>
      <p>CPU info: {{ ansible_facts['processor'][5] }}, vcpus: {{ ansible_facts['processor_vcpus'] }}</p>
      <p>MEM total: {{ ansible_facts['memtotal_mb'] }} MB</p>
      <p>DISK: {{ ansible_facts['devices']['vda']['partitions']['vda2']['size'] }}</p>
      <p>IP: {{ ansible_facts['default_ipv4']['address'] }}</p>
      </body></html>
    dest: /var/www/html/index.html
    mode: "0755"
    force: true

- name: Run daemon "apache2" and start it on boot
  ansible.builtin.systemd:
    name: apache2.service
    state: started
    enabled: true
    daemon_reload: true

- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://localhost