---
- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Install packet "apache2"
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Set index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Run daemon "apache2" and start it on boot
  ansible.builtin.systemd:
    name: apache2.service
    state: started
    enabled: true
    daemon_reload: true

- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://localhost