apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nedorezov-redis.fullname" . }}
  labels:
    {{- include "nedorezov-redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nedorezov-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nedorezov-redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "{{ .Values.volumes.mountPath }}"
              name: nedorezov-volume
          env:
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-auth
          ports:
            - containerPort: {{ .Values.service.port }}
      volumes:
      - name: nedorezov-volume
        hostPath:
          path: "{{ .Values.volumes.hostPath }}"
          type: DirectoryOrCreate
