version: '3.8'
 
services:
  nedorezovas-netology-db:
    image: postgres
    container_name: nedorezovas-netology-db
    ports:
      - "5432:5432"
    volumes:
      - ./netology/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: nedorezovas-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nedorezovas12!3!!
    networks:
      nedorezovas-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: unless-stopped

  nedorezovas-pgadmin:
    image: dpage/pgadmin4
    container_name: nedorezovas-pgadmin
    ports:
      - "61231:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nedorezovas@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    networks:
      nedorezovas-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: unless-stopped

  nedorezovas-zabbix-netology:
    image: zabbix/zabbix-server-pgsql
    container_name: nedorezovas-zabbix-netology
    links:
      - nedorezovas-netology-db    
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_DB: nedorezovas-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nedorezovas12!3!!
    ports:
    - "10051:10051"
    networks:
      nedorezovas-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: unless-stopped
 
  nedorezovas-netology-zabbix-frontend:
    image: zabbix/zabbix-web-apache-pgsql
    container_name: nedorezovas-netology-zabbix-frontend
    links:  
      - nedorezovas-netology-db
      - nedorezovas-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      DB_SERVER_PORT: 5432
      POSTGRES_DB: nedorezovas-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nedorezovas12!3!!
      ZBX_SERVER_HOST: "nedorezovas-zabbix-netology"
      ZBX_SERVER_PORT: 10051
      PHP_TZ: "Asia/Novosibirsk"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      nedorezovas-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: unless-stopped
 
networks:
  nedorezovas-my-netology-hw:    
    driver: bridge
    ipam:
      config:      
        - subnet: 172.22.0.0/24